// ?NORMINETTARE TUTTO
// !•memset
// !•bzero
// !•memcpy
// !•memccpy
// !•memmove
// !•memchr
// !•memcmp
// •strlen      L'ORIGINALE TORNA UN LD, LA MIA TORNA UN D. CAPIRE SE DEVO FAR TORNARE ANCHE IO UN LD
// •strlcpy     LA FUNZIONE NON LA TROVO NELLE LIB, DOVREBBERE ESSERE STATA TOLTA. L'ORIGINALE TORNA UN INT, LA MIA TORNA UN UNSIGNED INT. CAPIRE SE DEVO FAR TORNARE ANCHE IO UN INT.
// •strlcat     LA FUNZIONE NON LA TROVO NELLE LIB, DOVREBBERE ESSERE STATA TOLTA.
// !•strchr
// !•strrchr
// !•strnstr
// •strncmp
// !•atoi
// •isalpha     IL MAN DICE CHE DEVE TORNARE UN NON-ZERO CHAR, IO STO TORNANDO I VALORI CHE TORNANO NEI TEST
// •isdigit     IL MAN DICE CHE DEVE TORNARE UN NON-ZERO CHAR, IO STO TORNANDO I VALORI CHE TORNANO NEI TEST
// •isalnum     IL MAN DICE CHE DEVE TORNARE UN NON-ZERO CHAR, IO STO TORNANDO I VALORI CHE TORNANO NEI TEST
// •isascii     IL MAN DICE CHE DEVE TORNARE UN NON-ZERO CHAR, IO STO TORNANDO I VALORI CHE TORNANO NEI TEST
// •isprint     IL MAN DICE CHE DEVE TORNARE UN NON-ZERO CHAR, IO STO TORNANDO I VALORI CHE TORNANO NEI TEST
// !•toupper
// !•tolower