// ?NORMINETTARE TUTTO
// !•memset
// !•bzero
// !•memcpy
// !•memccpy
// !•memmove
// !•memchr
// !•memcmp
// •strlen      L'ORIGINALE TORNA UN LD, LA MIA TORNA UN D. CAPIRE SE DEVO FAR TORNARE ANCHE IO UN LD
// •strlcpy     LA FUNZIONE NON LA TROVO NELLE LIB, DOVREBBERE ESSERE STATA TOLTA. L'ORIGINALE TORNA UN INT, LA MIA TORNA UN UNSIGNED INT. CAPIRE SE DEVO FAR TORNARE ANCHE IO UN INT.
// •strlcat     LA FUNZIONE NON LA TROVO NELLE LIB, DOVREBBERE ESSERE STATA TOLTA.
// !•strchr
// !•strrchr
// !•strnstr
// •strncmp
// !•atoi
// •isalpha     UN SITO DICEVA CHE DOVEVA TORNARE 1 O 2, MA LA FUNZIONE ORIG TESTANDOLA TORNA 1024 O 0 (IO L'HO FATTA PRENDENDO AD ESEMPIO IL TEST); VERIFICARE.
// •isdigit     UN SITO DICEVA CHE DOVEVA TORNARE 1 O 2, MA LA FUNZIONE ORIG TESTANDOLA TORNA 1024 O 0 (IO L'HO FATTA PRENDENDO AD ESEMPIO IL TEST); VERIFICARE.
// !•isalnum
// !•isascii
// !•isprint
// !•toupper
// !•tolower